### PR TITLE
Add SXT

### PR DESCRIPTION
**Pull request by amo28**
All SXT engines used in the Real Fuels Stockalike config are configured for RealPlume. The only engines missing are the large 3.75m and 5m Saturn engines in the SXT pack. Vernier engine is also not fully tested yet, so not included in this merge.

### CODE REVIEW

**Comment by Felger** [comment]
These look pretty good, though your ModuleEngineConfigs will only apply to the first config it finds.  Try this instead:

```
	@MODULE[ModuleEngineConfigs]
	{
		%type = ModuleEnginesRF
		@CONFIG,*
		{
			%powerEffectName = Hypergolic-OMS-White
		}
	}
```

Otherwise these look good!

**Comment by Felger** [comment]
I'll fix it myself, no problemo.

**Comment by amo28** [comment]
Now that you've made the changes, I see the reason for them. Learned something new! Thanks! I'll make sure to keep the stock and RF compatibility separate next time as well.

**Comment by Felger** [comment]
Thanks for building the configs though, that's the long part!

**Pull request merged**
