### PR TITLE
Taerobee, SpaceY Expanded and Taurus HCV configs and TantaresLV updates

### PR DESCRIPTION
**Pull request by DerpyFirework**
Configs for Taurus HCV, the new SpaceY expanded pack, and the Taerobee pack. Also includes updates to TantaresLV.

### CODE REVIEW

**Comment by DerpyFirework** [comment]
Just updated the SpaceY-Expanded configs and ran into an issue. SpaceY-Expanded makes the "Penguin" Engines switchable between LFO and LHO from CryoEngines. Only problem with this is the patch runs after RealPlume has cleared the EFFECTS node, so the engage and flameout effects are messed up. Any ideas on how to fix this?

**Comment by Felger** [comment]
Do you have a link to the config that's causing problems?

**Comment by DerpyFirework** [comment]
The configs from SpaceY-Expanded are embedded in the actual engine configs (SYengine3mP1, SYengine5mP2 and SYengine7mP4)

**Comment by Felger** [comment]
Can you pastebin the ModuleManager.ConfigCache entry for the part that's messing up?

**Comment by DerpyFirework** [comment]
Thanks for the pointer to the ConfigCache! Didn't think to check that to see what could be done. Got it all working now, although it probably could be done better.

**Comment by Felger** [comment]
Awesome! Merging.

**Pull request merged**
