### PR TITLE
Tweaks and ReStock(Plus) support

### PR DESCRIPTION
**Pull request by Vladimir-csp**
Now that ReStock has been released, here are updates for it, and Stock.

### Stock:
* Rebalanced Reliant and Swivel
* Normalized Spark and Twitch to use OMS-Red, Ant and Spider to use OMS-White
* Rebalanced SRBs
(There is still something wrong with Flea and Hammer, looks like stock plume is not overridden)

### ReStock:
* Added tweaks for ReStock
* Added support for ReStockPlus
* (ReStock* stuff requires a new dirty plume to put on turbopump exhausts)
* ~~(No patch for RAPIER yet)~~
* ~~(Vector has a problem with shock cone position)~~

### CODE REVIEW

**Comment by Vladimir-csp** [comment]
There is a problem with RAPIER: plume originates at a slightly different height for each nozzle, but thrustTransform positions in the model [are leveled](https://github.com/PorktoberRevolution/ReStocked/issues/533#issuecomment-472125573)

plume_h

Where might this discrepancy originate?

**Comment by lmtz2000** [comment]
Hello, 
I see that the reliant and swivel engines were rebalanced according to the posts above. My question is how do I apply that to my game? Do I have to edit the config files? or can I download something and simply put in in the game data?

Thanks

**Comment by Vladimir-csp** [comment]
Rebalance means plume length and size were adjusted to mesh well with engines' power level (Reliant now rightfully has bigger flame than Swiwel).

The pull request kindly lists the changed files for you.
(or you can get them from [here](https://github.com/Vladimir-csp/RealPlume-StockConfigs/tree/master/GameData/RealPlume-Stock/Squad) and [here](https://github.com/Vladimir-csp/RealPlume-StockConfigs/tree/master/GameData/RealPlume-Stock/ReStockPlus))

**Comment by TomVorat** [comment]
when will the RealPlume/ReStock Update/Patch come out?

**Comment by TykoTek** [comment]
The plume for the Swivel is starting too deep in the bell such that the plume appears to expand through the bell - 

screenshot_2019-06-02--13-24-52

screenshot_2019-06-02--12-37-06

**Comment by TykoTek** [comment]
I added a line to remove other plumes to your liquidEngine2 config and it worked. The problem above was fixed. I'm not sure where the other plume was coming from, but this fixed it - 

`@PART[liquidEngine2]:FOR[RealPlume]:NEEDS[SmokeScreen] // LV-T45 "Swivel" Liquid Fuel Engine
{

	**!PLUME {}** 
	
	PLUME
    {
        name = Kerolox-Upper
        transformName = thrustTransform
        localRotation = 0,0,0
        flarePosition = 0,0,0.45
        plumePosition = 0,0,0.6
	plumeScale = 0.3
        flareScale = 0.45
        energy = 0.8
        speed = 0.6
    }
    @MODULE[ModuleEngines*]
    {
        %powerEffectName = Kerolox-Upper
		!runningEffectName = DELETE
    }
}
`

**Comment by Scialytic** [comment]
I believe I have solved the RAPIER mystery.

**Comment by Vladimir-csp** [comment]
> The plume for the Swivel is starting too deep in the bell such that the plume appears to expand through the bell -

I can not reproduce this with my configs, are you sure you replaced all files correctly?

screenshot1

**Comment by TykoTek** [comment]
I fixed it by adding the !PLUME {}     before the rest of the code as I mentioned above. I can only assume I'm getting another plume config from somewhere though I checked and I don't know where it could be coming from. I'll try it again this afternoon on fresh install.

**Comment by GHrynk** [comment]
I've seen the same problem as TykoTek with the engine plumes being too deep inside the engine bells on the Swivel and Reliant when using the ReStock models - and something else....  I tried applying the !PLUME {} code in my cfg files and it seemed to position the plumes correctly, but I'm not getting any change in the plume shape (expanding to large diffuse cloud) when I transition from atmosphere to vacuum.  I suspect the new code is just blanking out Real Plume action.

I tried a fresh install with just ReStock, ReStockPlus, and RealPlume, Smokescreen, and RealPlumeStock #81.  The plume effects DO work correctly there, so there's something else going on.  I'm going to try adding mods from my main install to see if I can narrow it down.

TykoTek, if you figure out who the culprit is, please post here and perhaps notify the owner of the mod if you see how to fix it.

**Comment by GHrynk** [comment]
TykoTek and Vladimir-csp, I've found the problem.  It's not Missing History per se, but it's the ReaPlumeStock patches for Missing History that's conflicting with ReStock.  I've previously deleted the duplicate engines from MH that correspond to their equivalents in ReStockPlus (T-15, LV-303, LV-909 reskin) but for some reason MH has some T-30 and T-45 patches in RealPlumeStock as well.  I'm assuming they're in there for a reason, but I haven't pulled the thread on why yet.

**Comment by TomVorat** [comment]
Will RealPlume support be added for the Flea and Hammer?

**Comment by zorg2044** [comment]
@Vladimir-csp Thanks for working on this PR, it provided a good solution for a lot of people using your fork in the past few months.

However I will be closing this without merging as I have just recently taken over maintenance of both this and RealPlume core itself. I have added around 20 brand new prefabs based on particle FX originally included in ReStock, NearFuture, CryoEngines and PlumeParty. 

https://github.com/KSP-RO/RealPlume/issues/47

The Development branch of RealPlumeStock now has these plumes applied to ReStock parts instead of adjusting existing ones (with a few exceptions that use exisiting prefabs).

https://github.com/KSP-RO/RealPlume-StockConfigs/issues/87

I will be releasing the updated RealPlume and RealPlume-Stock after a few days of testing.

**Pull request closed without merging**
