### PR TITLE
Space Shuttle program mod config.

### PR DESCRIPTION
**Pull request by nansuchao**
It was more difficult to reach this point that to create the config... :-)))))

### CODE REVIEW

**Comment by Felger** [comment]
Awesome! Did you have any trouble getting the flare/plume to line up well? There are a couple of optional parameters available to adjust those if you want.

**Comment by nansuchao** [comment]
It was really easy to create config for this mod. Interstellar is
difficult, due to the futuristic bell and various propellant.

Il lunedì 14 settembre 2015, Felger <notifications@github.com> ha scritto:

**Comment by Felger** [comment]
Yeah, I really need to just create some effects for those. Eventually.

**Comment by nansuchao** [comment]
The SSME effects remember the "Low Profile Atlas" from B9. I want to learn
how to create new particles, so maybe I can contribute...

Il lunedì 14 settembre 2015, Felger <notifications@github.com> ha scritto:

> Yeah, I really need to just create some effects for those. Eventually.
>
> On Mon, Sep 14, 2015 at 2:11 PM, nansuchao <notifications@github.com

**Comment by Felger** [comment]
Sure! Have a look at the EFFECT configs in RealPlume/000_GenericPlumes/
 That'll give you a good starting point.  Feel free to ask me any questions
you have, or look at the SmokeScreen documentation.  Making the configs is
certainly more art than science, although getting them to resemble
real-life rockets is a bit of both.

**Comment by nansuchao** [comment]
Thanks, I will, from the next week. I'm on holiday until next monday.

Il lunedì 14 settembre 2015, Felger <notifications@github.com> ha scritto:

> Sure! Have a look at the EFFECT configs in RealPlume/000_GenericPlumes/
> That'll give you a good starting point. Feel free to ask me any questions
> you have, or look at the SmokeScreen documentation. Making the configs is
> certainly more art than science, although getting them to resemble
> real-life rockets is a bit of both.
>
> On Mon, Sep 14, 2015 at 2:28 PM, nansuchao <notifications@github.com

**Pull request merged**
