### PR TITLE
Plume patching refactor

### PR DESCRIPTION
**Pull request by PhineasFreak**
**Change log:**

* Remove all instances of ModuleEnginesFX from the plume configs.
* Add some global patches to patch:
    - Physicless engines to have physics significance (or else it breaks the plume configs).
    - All baseline "ModuleEngines" modules to the proper "ModuleEnginesFX" variant (leaves alternate engine modules from AJE and RF untouched).
    - Remove the deprecated (by SmokeScreen) "fxOffset" field.
* Add a plume config template.
* Add newlines (for GitHub).

**Notes:**

* Under no circuimstances a plume should contain a "ModuleEnginesFX" field.
* It has not been extensively tested so there might be bugs. Test and report back!

### CODE REVIEW

**Comment by DerpyFirework** [comment]
I think I see a problem in the global ModuleEngines patch.
It looks for every part with ModuleEngines, but does not also check if they have a plume attached.
In the case of an engine with no RealPlume config and is using ModuleEngines, it would remove the effects entirely (I think).
Checking for ModuleEngines and a PLUME node would avoid such an issue

**Comment by PhineasFreak** [comment]
There is no reason to check the baseline ModuleEngines for an EFFECTS node because it is impossible to add such a node to it in the first place. You need to use either the stock ModuleEnginesFX or similar modules that are derived from it (AJE, RF to name a few).

Also, nowhere in these patches i remove the FX fields. You would need to define some MM fields like these to do so: https://github.com/KSP-RO/RealPlume/blob/master/GameData/RealPlume/000_Generic_Plumes/000_EFFECTS_Remover.cfg

**Comment by DerpyFirework** [comment]
I've just done some testing, and it would seem ModulEnginesFX does not use those FX fields, so you end up with this on engines with no RP config:
screenshot7
Adding the check for a PLUME fixes this:
screenshot8

**Comment by Nhawks1717** [comment]
Did you add the check for the plume in the global config?

**Comment by PhineasFreak** [comment]
Just got around it and fixed it.

**Comment by Nhawks1717** [comment]
Okay so everything should be good now to merge?

**Comment by PhineasFreak** [comment]
Let's see if @DerpyFirework finds anything else. Slow and steady wins the race! :wink:

**Comment by DerpyFirework** [comment]
I can't see any further issues, so should be good.

**Comment by PhineasFreak** [comment]
@DerpyFirework BTW, the "test" engine was just that, a copy of one of the stock engines without a RealPlume config?

**Comment by DerpyFirework** [comment]
@PhineasFreak yes, I used a quick MM patch to duplicate the LV-T30, the stock one worked perfectly

**Comment by Nhawks1717** [comment]
:D Thanks for the work on this guys, it means a lot. I will look over all of the changes tomorrow and then push these changes to the master branch so I can begin the rewrites on engines that need it. Thank you again Phineas for helping out with this!

**Comment by PhineasFreak** [comment]
@DerpyFirework OK, because for a moment i though that the patch that converts the ModuleEngines to ModuleEnginesFX did not work... :sweat_smile:

@Nhawks1717 no problem mate! Now, if only i could do the same for RO...

**Pull request merged**
